plugins {
    id 'java'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'com.gradleup.shadow' version '9.4.1'
}

shadowJar {
    archiveClassifier.set('')
    from('.') {
        include 'module.json'
    }
}

group = 'com.centralcore.modules'
version = '0.1.0'

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

javafx {
    version = '21'
    modules = ['javafx.controls', 'javafx.fxml', 'javafx.graphics']
}

dependencies {
    implementation 'com.google.code.gson:gson:2.10.1'
    compileOnly rootProject.project(':core').sourceSets.main.output
}

sourceSets {
    main {
        java {
            srcDirs = ['src']
        }
        resources {
            srcDirs = ['resources']
        }
    }
}

jar {
    archiveFileName = 'CitizenModule.jar'
}

tasks.named('build') {
    dependsOn tasks.named('shadowJar')
}